config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
  devise_scope :user do
  get 'users/registrations/edit_confirmation' => 'users/registrations#edit_confirmation'
  post 'users/guest_sign_in' =>'users/sessions#new_guest'
  end

  root to: 'posts#index'
  get 'rooms/:id' => 'rooms#show', as:'rooms'
  resources :messages, only: :create
  get 'posts/new' => 'posts#new'
  get 'posts/rec' => 'posts#rec'
  get 'posts/edit_confirmation' => 'posts#edit_confirmation'
  get 'posts/edit_change' => 'posts#edit_change'
  get 'posts/all_content' => 'posts#all_content'
  get 'posts/search_posts' => 'posts#search_posts'
  get 'posts/mypage' => 'posts#mypage'
  get 'posts/:id' =>'posts#show'
  post 'posts/create' => 'posts#create'
  get 'posts/:id/edit' => 'posts#edit'
  patch 'posts/:id' => 'posts#update'
  delete 'posts/:id' => 'posts#destroy'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one :room
  accepts_nested_attributes_for :room

  validates :user_id, presence: true
  validate :chess_validate
  validate :app_validate
  validate :time_validate
  validate :all_tag_validate
  validate :content_validate

  private


  def chess_validate
    if chess.blank?
      errors.add(:chess, "を入力してください")
    elsif chess.length > 10
      errors.add(:chess, "は10文字以内にしてください")
    end
  end
  def app_validate
    if app.blank?
      errors.add(:app, "を入力してください.")
    elsif app.length > 30
      errors.add(:app, "は30文字以内にしてください")
    end
  end
  def time_validate
    if time.blank?
      errors.add(:time, "を入力してください.")
    elsif time.length > 10
      errors.add(:time, "は10文字以内にしてください")
    end
  end
  def all_tag_validate
    if all_tag.length > 20
      errors.add(:all_tag, "は合計20文字以内にしてください")
    end
  end
  def content_validate
    if content.length > 100
      errors.add(:content, "は100文字以内にしてください")
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_target_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy, :mypage]
  before_action :check_guest, only: [:new, :create, :update, :destroy, :mypage]
  before_action :account_confirmation, only: [:edit, :update, :destroy]
  before_action :set_search

  def index
    @posts = Post.all.order(updated_at: "DESC").includes(:room).limit(10)
  end

  def new
    @post = Post.new
    @post.build_room
  end

  def mypage
    @posts = current_user.posts.page(params[:page])
    @messages = Message.all.includes(:room).where(user_id:current_user.id).order(updated_at: "DESC")
    @ary = []
  end

  def all_content
    @posts = Post.page(params[:page]).order(updated_at: "DESC").includes(:room)
  end

  def search_posts
    @q = Post.ransack(params[:q])
    grouping_hash = params[:q][:app_or_chess_or_time_or_all_tag_cont].split(",").reduce({}){|hash, word| hash.merge(word => { app_or_chess_or_time_or_all_tag_cont: word })}
    @posts = Post.ransack({ combinator: 'and', groupings: grouping_hash }).result.includes(:room).order(updated_at: "DESC").page(params[:page])
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = "#{@post.user.username}が#{@post.room.name}を作成しました。"
      redirect_to("/")
    else
      render("posts/new")
    end
  end

  def show
    @room = @post.room
    @url = request.url
  end

  def edit
  end

  def update
      if @post.update(post_params)
        flash[:notice] = "更新しました。"
        redirect_to("/")
      else
        render("posts/edit")
      end
  end

  def destroy
    if @post.destroy
      flash[:notice] = "「#{@post.room.name}」が削除されました。"
      redirect_to("/")
    else
      render("posts/edit")
    end
  end

  private


  def post_params
    params.require(:post).permit(:content, :app, :time, :chess, :all_tag, room_attributes:[:id, :name])
  end

  def set_target_post
    @post = Post.find(params[:id])
  end

  def account_confirmation
    unless current_user.id == @post.user_id
    flash[:notice] = "このアカウントは操作できません。"
      redirect_to("/")
    end
  end

end

app/helpers/post_helper.rb
module PostHelper
end

app/views/posts/all_content.html.erb
<ul class="cp_breadcrumb">
	<li><a href="/">ホーム</a></li>
	<li><a href="">投稿一覧</a></li>
</ul>
<div class="all_contnnt_body">
	<div class="main_title">
		<h1>一覧</h1>
	</div>
	<div class="container">
		<div class="row main_wrap">
      <% @search_posts.each do |post| %>
			<div class="col-lg-6 col-12">
				<a href="/posts/<%="#{post.id}" %>" style="text-decoration:none;">
					<div class="main_content">
						<div class="main_card paper paper-curl-right">
							<h2><%= post.room.name %></h2>
							<p>対戦したいアプリ：<%=  content_tag :span, post.app, class: "index_tag"%></p>
							<p>棋力：<%= post.chess %></p>
							<p>持ち時間：<%= post.time %></p>
							<p><%= post.content %></p>
			 				<span class="card_tag">#<%= post.all_tag %></span>
							<p class="card_time"><%= l post.created_at, format: '%-m月%-d日(%a) %H:%M' %></p>
						</div>
					</div>
				</a>
			</div>
			<% end %>
		</div>
	</div>
	<div class="paginete_wrap">
		<%= paginate @posts %>
	</div>
</div>

app/views/posts/edit.html.erb
<ul class="cp_breadcrumb">
	<li><a href="/">ホーム</a></li>
	<li><a href="/posts/<%="#{@post.id}" %>">詳細</a></li>
	<li><a href="">投稿編集</a></li>
</ul>
<div class="container">
  <div id="wrap" class="single">
    <h1 class="post-heading">投稿編集</h1>
    <div class="inputInformation">
      <p>下記の内容をご入力の上、お進みください。</p>
    </div>
    <%= form_for(@post, :url => {:controller => :posts, :action => :update})  do |f| %>
      <% if @post.errors.any? %>
        <div id="error_explanation">
          <h3 style="color:red;">
          <%= I18n.t("errors.messages.not_saved",
                   count: @post.errors.count,
                   resource: @post.class.model_name.human.downcase)
           %>
          </h3>
          <ul>
            <% @post.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.fields_for :room do |i| %>
        <div class="form-group">
          <%= i.label :name, '部屋名*' %>
          <%= i.text_field :name, class: 'form-control'%>
          <small id="poster-tip" class="form-text text-muted">
            部屋の名前を決めてください。
          </small>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :chess, '棋力*' %>
        <%= f.text_field :chess, class: 'form-control tagsinput',value: current_user.chess %>
        <small id="poster-tip" class="form-text text-muted">
          自分の棋力を入力してください。
        </small>
      </div>
      <div class="form-group">
        <%= f.label :app, '使用するアプリ*' %>
        <%= f.text_field :app, class: 'form-control tagsinput',value: current_user.app %>
        <small id="poster-tip" class="form-text text-muted">
          希望するアプリを入力してください。
        </small>
      </div>
      <div class="form-group">
        <%= f.label :time, '対戦時間*' %>
        <%= f.text_field :time, class: 'form-control tagsinput',value: current_user.time %>
        <small id="poster-tip" class="form-text text-muted">
          希望する対戦時間を入力してください。
        </small>
      </div>
      <div class="form-group">
        <%= f.label :all_tag, 'タグ' %>
        <%= f.text_field :all_tag, class: 'form-control', id: 'tags_all' %>
        <small id="poster-tip" class="form-text text-muted">
          好きなタグをつけることができます。
        </small>
      </div>
      <div class="form-group">
        <%= f.label :content, '募集内容' %>
        <%= f.text_area :content, class: 'form-control'%>
        <small id="poster-tip" class="form-text text-muted">
          募集内容を入力してください。
        </small>
      </div>
      <div class="buttonContainer">
        <%= f.submit '編集', class: 'btn btn-primary buttonConfirm' %>
      </div>
      <div class="buttonContainer">
				<%= link_to '削除', "/posts/#{@post.id}", method: :delete, class:"btn btn-danger buttondestroy", data: {confirm: "削除しますか？"} %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<header>
  <% if notice %>
     <p class="alert alert-notice"><%= notice %></p>
   <% end %>
   <% if alert %>
     <p class="alert alert-error"><%= alert %></p>
   <% end %>
  <nav class="navbar navbar-expand-lg navbar-light justify-content-around">
    <a class="navbar-brand top-icon" href="/">
      <h1 style="color:#FFF;">ノシ将棋</h1>
    </a>
    <%= search_form_for @q, url: posts_search_posts_path, class:"ml-4 w-75 d-inline center-block" do |f| %>
      <div class="input-group header_top">
        <%= f.search_field :app_or_chess_or_time_or_all_tag_cont, placeholder: '何でも検索...', class: 'form-control', id: 'tags_top'%>
        <%= f.submit ("🔍"), class: 'btn btn-secondary' %>
      </div>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <% unless current_user.email == 'guest@example.com' %>
            <li class="nav-item active">
              <%= link_to 'アカウント編集', users_registrations_edit_confirmation_path, class: 'nav-link  index-nav' %>
            </li>
          <% end %>
          <li class="nav-item active">
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link  index-nav ' %>
          </li>
        <% else %>
          <li class="nav-item active">
            <%= link_to "新規登録", new_user_registration_path, class: 'nav-link  index-nav ' %>
          </li>
          <li class="nav-item active">
            <%= link_to "ログイン", new_user_session_path, class: 'nav-link  index-nav ' %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
<section id="mainvisual"></section>
</header>

<div class="reserv_post">
  <a href="/posts/new" style="text-decoration: none;">投稿↑</a>
</div>
<div class="reserv_mypage">
  <a href="/posts/mypage" style="text-decoration: none;">マイページ↑</a>
</div>

<main>
  <div class="rec_body">
    <h3 class="rec-title1">遊びましょう。同じアプリで。同じレベルで。</h3>
    <h5 class="rec-title2">このサイトは将棋専門の投稿掲示板です。</h5>
    <h5 class="rec-title3">チャットルームも用意してありますので、</h5>
    <h5 class="rec-title4">もし時間がある方は感想戦まで行ってみてはいかががですか。</h5>
  </div>
  <div class="main_body">
    <div class="main_title">
      <h1>一覧</h1>
    </div>
    <div class="container">
      <div class="row main_wrap">
        <% @posts.each do |post| %>
          <div class="col-lg-6 col-12">
            <a href="/posts/<%="#{post.id}" %>" style="text-decoration:none;" id="show_link">
              <div class="main_content">
                <div class="main_card">
                  <h2><%= post.room.name %></h2>
                  <p>対戦したいアプリ：<%=  content_tag :span, post.app, class: "index_tag"%></p>
                  <p>棋力：<%= post.chess %></p>
                  <p>持ち時間：<%= post.time %></p>
                  <p><%= post.content %></p>
                  <span class="card_tag">#<%= post.all_tag %></span>
                  <p class="card_time"><%= l post.created_at, format: '%-m月%-d日(%a) %H:%M' %></p>
                </div>
              </div>
            </a>
          </div>
        <% end %>
      </div>
      <div class="view-more">
        <button class="learn-more">
          <span class="circle" aria-hidden="true">
            <span class="icon arrow"></span>
          </span>
          <a href="/posts/all_content">
          <span class="button-text">もっと見る</span>
          </a>
        </button>
      </div>
    </div>
  </div>
</main>

app/views/posts/mypage.html.erb
<ul class="cp_breadcrumb">
	<li><a href="/">ホーム</a></li>
	<li><a href="">マイページ</a></li>
</ul>
<div id="mypagewrap">
  <h1 class="mypage-heading">マイページ</h1>
  <ul class="nav nav-tabs" id="myTab" role="tablist", style="padding-top:50px">
    <li class="nav-item">
      <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="Home" aria-selected="true">投稿一覧</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="Profile" aria-selected="false">メッセージ</a>
    </li>
  </ul>
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
      <div class="container">
        <div class="row main_wrap">
          <% @posts.each do |post| %>
						<div class="col-lg-6 col-12">
							<a href="/posts/<%="#{post.id}" %>" style="text-decoration:none;">
								<div class="main_content">
									<div class="main_card">
										<h2><%= post.room.name %></h2>
										<p>対戦したいアプリ：<%=  content_tag :span, post.app, class: "index_tag"%></p>
										<p>棋力：<%= post.chess %></p>
										<p>持ち時間：<%= post.time %></p>
										<p><%= post.content %></p>
										<span class="card_tag">#<%= post.all_tag %></span>
										<p class="card_time"><%= l post.created_at, format: '%m月%-d日(%a) %H:%M' %></p>
									</div>
								</div>
							</a>
						</div>
          <% end %>
        </div>
      </div>
					<%= paginate @posts %>
    </div>
    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
      <div class="container">
        <div class="mypage_message_wrap">
          <% @messages.each do |message| %>
            <% unless @ary.include?(message.room.id) %>
              <% num_content = message.content.last(1) %>
              <a href="/rooms/<%="#{message.room.id}" %>" style="text-decoration:none;">
	              <div class="mypage_message_body">
	                <div class="mypage_message_title">
	                  <p class="mypage_message_text">部屋名：<%= message.room.name %></p>
											<span style="float:right; padding-right:50px;"><%= l message.created_at, format: '%m月%-d日(%a) %H:%M' %></span>
	                </div>
	                <div class="mypage_message_content">
	                  <p class="mypage_message_text"><%= message.content %></p>
	                </div>
	              </div>
            	</a>
            	<% @ary.unshift(message.room.id) %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<ul class="cp_breadcrumb">
	<li><a href="/">ホーム</a></li>
	<li><a href="">投稿</a></li>
</ul>

<div class="container">
  <div id="wrap" class="single">
    <h1 class="post-heading">投稿</h1>
    <div class="post-explanation">
      <h2 class="explanation-title">
        賢く投稿を行うために。
      </h2>
      <div class="explanation-body">
        <ul class="explanation-show">
          <li>１．使用するアプリ名は正式名を入力していただくと検索にかかりやすいです。</li>
          <li>２．棋力はそのアプリの棋力、または自分の推定棋力を入力してください。</li>
        </ul>
      </div>
    </div>
    <div class="inputInformation">
      <p>下記の内容をご入力の上、お進みください。</p>
    </div>

    <%= form_for(@post, :url => {:controller => :posts, :action => :create})  do |f| %>
      <% if @post.errors.any? %>
        <div id="error_explanation">
          <h3 style="color:red;">
          <%= I18n.t("errors.messages.not_saved",
                     count: @post.errors.count,
                     resource: @post.class.model_name.human.downcase)
           %>
          </h3>
          <ul>
            <% @post.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.fields_for :room do |i| %>
        <div class="form-group">
          <%= i.label :name, '部屋名*' %>
          <%= i.text_field :name, class: 'form-control'%>
          <small id="poster-tip" class="form-text text-muted">
            部屋の名前を決めてください。
          </small>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :chess, '棋力*' %>
        <%= f.text_field :chess, class: 'form-control tagsinput',value: current_user.chess %>
        <small id="poster-tip" class="form-text text-muted">
          自分の棋力を入力してください。
        </small>
      </div>
      <div class="form-group">
        <%= f.label :app, '使用するアプリ*' %>
        <%= f.text_field :app, class: 'form-control tagsinput',value: current_user.app %>
        <small id="poster-tip" class="form-text text-muted">
          希望するアプリを入力してください。
        </small>
      </div>
      <div class="form-group">
        <%= f.label :time, '対戦時間*' %>
        <%= f.text_field :time, class: 'form-control tagsinput',value: current_user.time %>
        <small id="poster-tip" class="form-text text-muted">
          希望する対戦時間を入力してください。
        </small>
      </div>
      <div class="form-group">
        <%= f.label :all_tag, 'タグ' %>
        <%= f.text_field :all_tag, class: 'form-control', id: 'tags_all' %>
        <small id="poster-tip" class="form-text text-muted">
          好きなタグをつけることができます。
        </small>
      </div>
      <div class="form-group">
        <%= f.label :content, '募集内容' %>
        <%= f.text_area :content, class: 'form-control'%>
        <small id="poster-tip" class="form-text text-muted">
          募集内容を入力してください。
        </small>
      </div>
      <div class="buttonContainer">
        <%= f.submit '投稿', class: 'btn btn-primary buttonConfirm' %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/search_posts.html.erb
<ul class="cp_breadcrumb">
	<li><a href="/">ホーム</a></li>
	<li><a href="">投稿一覧</a></li>
</ul>
<div class="all_contnnt_body">
	<div class="main_title">
		<h1>一覧</h1>
	</div>
	<div class="container">
		<div class="row main_wrap">
      <% @posts.each do |post| %>
			<div class="col-lg-6 col-12">
				<a href="/posts/<%="#{post.id}" %>" style="text-decoration:none;">
					<div class="main_content">
						<div class="main_card paper paper-curl-right">
							<h2><%= post.room.name %></h2>
							<p>対戦したいアプリ：<%=  content_tag :span, post.app, class: "index_tag"%></p>
							<p>棋力：<%= post.chess %></p>
							<p>持ち時間：<%= post.time %></p>
							<p><%= post.content %></p>
			 				<span class="card_tag">#<%= post.all_tag %></span>
							<p class="card_time"><%= l post.created_at, format: '%-m月%-d日(%a) %H:%M' %></p>
						</div>
					</div>
				</a>
			</div>
			<% end %>
		</div>
	</div>
	<div class="paginete_wrap">
		<%= paginate @posts %>
	</div>
</div>

app/views/posts/show.html.erb
<ul class="cp_breadcrumb">
	<li><a href="/">ホーム</a></li>
	<li><a href="">詳細</a></li>
</ul>
<section id="show-main">
  <div class='show-message'>
    <%= @post.user.content %>
  </div>
	<div class="show-post">
		<div class="confirmation_form">
			<h5 class=confirmation_wrap>部屋名</h5>
			<p class="confirmation_text"><%= @room.name %></p>
		</div>
    <div class="confirmation_form">
      <h5 class=confirmation_wrap>棋力</h5>
      <p class="confirmation_text"><%= @post.chess %></p>
    </div>
    <div class="confirmation_form">
      <h5 class=confirmation_wrap>対戦したいアプリ</h5>
      <p class="confirmation_text"><%= @post.app %></p>
    </div>
    <div class="confirmation_form">
      <h5 class=confirmation_wrap>対戦時間</h5>
      <p class="confirmation_text"><%= @post.time %></p>
    </div>
    <div class="confirmation_form">
      <h5 class=confirmation_wrap>タグ</h5>
      <p class="confirmation_text"><%= @post.all_tag %></p>
    </div>
    <div class="confirmation_form">
      <h5 class=confirmation_wrap>募集内容</h5>
      <p class="confirmation_text"><%= @post.content %></p>
    </div>
	</div>
    <div class="show-button_left">
			<%= link_to 'チャットルーム',"/rooms/#{@room.id}", class: "btn-circle-3d", style:"text-decoration: none; color:#fff;" %>
    </div>
    <div class="show-button_right">
			<div class="btn-circle-3d" style="background:#00CC99" id="copybtn">URLコピー</div>
    </div>
		<% if user_signed_in? %>
			<% if @post.user_id == current_user.id then %>
				<div class="show-button_center">
					<%= link_to '編集',"/posts/#{@post.id}/edit", class: "btn-circle-3d", style:"text-decoration:none; color:#fff; background:#FF3366;" %>
				</div>
			<% end %>
		<% end %>

    <div class='show_bottom-content'>
      <svg class='pricing-deco-img' enable-background='new 0 0 300 100' height='300px' id='Layer_1' preserveAspectRatio='none' version='1.1' viewBox='0 0 300 100' width='100%' x='0px' xml:space='preserve' y='60px'>
        <path class='deco-layer deco-layer--1' d='M30.913,43.944c0,0,42.911-34.464,87.51-14.191c77.31,35.14,113.304-1.952,146.638-4.729&#x000A;	c48.654-4.056,69.94,16.218,69.94,16.218v54.396H30.913V43.944z' fill='#FFFFFF' opacity='0.6'></path>
        <path class='deco-layer deco-layer--2' d='M-35.667,44.628c0,0,42.91-34.463,87.51-14.191c77.31,35.141,113.304-1.952,146.639-4.729&#x000A;	c48.653-4.055,69.939,16.218,69.939,16.218v54.396H-35.667V44.628z' fill='#E9908A' opacity='0.6'></path>
        <path class='deco-layer deco-layer--3' d='M43.415,98.342c0,0,48.283-68.927,109.133-68.927c65.886,0,97.983,67.914,97.983,67.914v3.716&#x000A;	H42.401L43.415,98.342z' fill='#FFFFFF' opacity='0.7'></path>
        <path class='deco-layer deco-layer--4' d='M-34.667,62.998c0,0,56-45.667,120.316-27.839C167.484,57.842,197,41.332,232.286,30.428&#x000A;	c53.07-16.399,104.047,36.903,104.047,36.903l1.333,36.667l-372-2.954L-34.667,62.998z' fill='#E9908A' height='500px'></path>
      </svg>
    </div>
</section>
<input id="copyTarget" type="text" style="width:100%; box-sizing:border-box" value="<%= @url %>" readonly>